project:
  type: website

website:
  title: "Paw Hansen"
  navbar:
    right:
      - href: blog.qmd
        text: Blog
      - href: research.qmd
        text: Research

format:
  html:
    code-fold: true
    code-summary: "Code"
    theme: 
      light: 
       - litera
       - custom.css
      dark: 
       - slate
       - custom.scss
    smooth-scroll: true
      



